config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'

  devise_for :users
  get 'sobre' => 'about#index'
  get 'regras' => 'regras#index'
  get 'welcome/index'
  root 'welcome#index'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
private
  def user_not_authorized
    flash[:notice] = "Você não tem permissão para fazer esta ação"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @users = User.all
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :conteudo, :data)
    end
end

app/controllers/regras_controller.rb
class RegrasController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/regras_helper.rb
module RegrasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<font size = 7, face = "Purisa"><center><h1>Feito para os peladeiros de plantão</h1><br></font>
  <font size = 4, face = "Purisa">
<h4>
• Para marcar as peladas de futebol.
<br><br>
• Use com moderação, a prática de futebol pode causar II/MI
<br><br>
• Criado por alunos de OO da Universidade de Brasília
<br><br>
• Para partilhar resultados humilhantes de seus "amiguinhos"
<br><br>
• Vamos que vamos \o/
<br><br>


</h4>

app/views/control_users/index.html.erb
  <center><br><font size = 3, face = "Purisa"><h1>Listing Users</h1></center>

<table>
  <thead>
    <tr>
      <font size = 3, face = "Purisa"><th>email</th>
      <font size = 3, face = "Purisa"><th><th>role</th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

</tbody>
<% @users.each do |user| %>
<tr>
    <center><font size = 3, face = "Purisa"><td><%= user.email %></td></center>
    <center><font size = 3, face = "Purisa"><td><td><%= user.role %></td></td></center>
</tr>
<% end %>
</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Streetfut" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <head>
    <title>DIV - Transparente</title>
    <style type="text/css">
    #div {
    	position:absolute;
    	left:268px;
    	top:116px;
    	width:11px;
    	height:12px;
    	z-index:1;
    	opacity:.6;
    	background-color: #FFFFFF;
    }
    </style>
</head>
<head>
	<style>
	#box{
		height: 220px;
		width:165px;
		border:1px solid;
		background-image:url('bg.jpg');
		background-position: center
	}
	</style>
</head>
    <div  class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <b><font face="Purisa"><a class="navbar-brand" href="http://localhost:3000/">Streetfut</a></font><br>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul><ul><ul><ul><ul><ul><ul>
            <ul><ul><ul><ul><ul><ul><ul>
              <ul><ul><ul><ul><ul><ul>
                <ul><ul><ul><ul><ul class="nav navbar-nav">
            <font size=4 face="Purisa" ><li><%= link_to "Sobre", "sobre" %></font>
            <ul><font size=4 face="Purisa"><%= link_to "Regras", "regras"  %></li></font></ul>
          </ul></ul></ul></ul></ul></ul>
          </ul></ul></ul></ul></ul></ul></ul>
        </ul></ul></ul></ul></ul></ul></ul>
      </ul></ul></ul></ul></ul>
        </div>
      </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <center><br><br><p>&copy; Vinicius&Gustavo 2016</p></center>
      </footer>

    </div> <!-- /container -->
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

  <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:titulo) %>
  </div>
  <div class="form-group">
    <%= f.label :conteudo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :conteudo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:conteudo) %>
  </div>
  <div class="form-group">
    <%= f.label :data, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :data, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
    <font size = 3, face = "Purisa"><h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:conteudo) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>

    </tr>
  </thead>
  <center>Eae <%= current_user.email  %> de Boas ?</center>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <br><td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.titulo %></td>
        <td><%= post.conteudo %></td>
        <td><%= post.data %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
        <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<font face="Purisa"><%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @post.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:conteudo) %>:</strong></dt>
  <dd><%= @post.conteudo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @post.data %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'%>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/regras/index.html.erb
<font size = 7, face = "Purisa"><center><h1>Regras do Forum</h1><br></font>
  <font size = 4, face = "Purisa">
<h4>Regras em geral que devem ser cumpridas para garantir um ótimo espaço de amizade entre os participantes. Disso faz parte;
<br>
<br>


• E bom lembra que por traz de cada usuário tem um ser humano.
<br><br>
• Que cada um vai respeitar os outros membros e as suas opiniões da mesma maneira que ele gosta de ser respeitado.
<br><br>
• Que possivelmente menores de 18 anos também podem participar deste Fórum.
<br><br>
• Que não há diferenças pessoais no fórum.
<br><br>
• Que é de fundamental importância se expressar de forma clara e cumprir as regras atuais de ortografias para evitar que haja maus entendimentos.
<br><br>
• Cada um tem responsabilidades pelas colocações publicadas e que e possivelmente tem que tirar as consequências.</h4>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>
<center><h1><b><font size = 14, face="Purisa"> Street Fut</font></b> <br /></h1></center>

<% if user_signed_in?%>
<ul>
  <center><br><font size = 3, face = "Purisa"><li><%= current_user.email %></li></font></center>
  <center><br><font size = 3, face = "Purisa"><li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li></center>
</ul>
<% else %>
  <ul>
    <center><br><font size = 3, face = "Purisa"><li><%= link_to "Cadastro de novo usuário", new_user_registration_path %></li></font></center>
    <center><br><br><font size = 3, face = "Purisa"><li><%= link_to "Logar", new_user_session_path %></li></font></center>
  </ul>
<% end %>

<ul>
  <center><br><br><font size = 3, face = "Purisa"><li><%= link_to "Posts", posts_path %></li></font></center>
  <center><br><br><font size = 3, face = "Purisa"><li><%= link_to "Usuários", control_users_index_path %></li></font></center>
</ul>